---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
      tags: [clickhouse, clickhouse-service]
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
          tags: [clickhouse, clickhouse-install]
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
          tags: [clickhouse, clickhouse-install]
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
      tags: [clickhouse, clickhouse-install]

    - name: Flush handlers
      meta: flush_handlers
      tags: [clickhouse, clickhouse-service]

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
      tags: [clickhouse, clickhouse-config]


- name : Install Vector
  hosts: clickhouse
  handers:
    - name: Restart vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
      tags: [vector, vector-service]

  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
        mode: "0644"
      tags: [vector, vector-install]
    
    - name: Install vector package
      become: true
      ansible.builtin.yum:
        name: "./vector-{{ vector_version }}.rpm"
        disable_gpg_check: true
      notify: Restart vector service
      tags: [vector, vector-install]
      
    - name: Deploy vector config
      become: true
      ansible.builtin.template:
        src: vector.toml.j2
        dest: /etc/vector/vector.toml
        owner: root
        group: root
        mode: "0644"
      notify: Restart vector service
      tags: [vector, vector-config]

    - name: Flush handlers
      meta: flush_handlers
      tags: [vector, vector-service]